name: ${project.name}
version: ${project.version}
main: com.lenis0012.loginsecurity.LoginSecurity
author: lenis0012, mirolm
description: ${project.description}
website: ${project.url}
commands:
  login:
    description: Log in to account
    usage: /login [password]
    aliases:
      - l
      - log
  register:
    description: Register an account
    usage: /register [password]
    aliases:
      - reg
  changepassword:
    description: Change password of an account
    usage: /changepassword [old] [new]
    aliases:
      - cp
      - changepass
