name: LoginSecurity
version: ${project.version}-${bukkitplugin.desc}
main: com.lenis0012.loginsecurity.LoginSecurity
author: lenis0012
description: ${project.description}
api-version: ${bukkitplugin.api}

commands:
  login:
    description: Log in to account
    usage: /login [password]
    aliases:
      - l
      - log
  register:
    description: Register an account
    usage: /register [password]
    aliases:
      - reg
  changepassword:
    description: Change password of an account
    usage: /changepass [old] [new]
    aliases:
      - cp
      - changepass
